### PR TITLE
Update to Nodev16 and the latest version of @actions/core.

### PR DESCRIPTION
**Pull request by Kiran-B**
This PR closes https://github.com/indiesdev/curl/pull/9, closes https://github.com/indiesdev/curl/issues/11 & closes https://github.com/indiesdev/curl/issues/12

Primary this PR includes two changes: 
1. Bump the version of `@actions/core` to 1.10.0. This should fix the usage of set-output.
2. Update `action.yml` to declare the usage of `Node v16`. And hence the update of `@types/node` in package.json.

PR also includes below non-essential changes:
1. Add `typescript` as a dev dependency. This is to remove the restriction of installing typescript as a global tool.
2. Add `build` & `clean` scripts to package.json for easier build.

### CODE REVIEW

**Comment by Kiran-B** [comment]
@indiesdev @wphromma @beetlikeyg087 @EndBug Apologies for tagging and bothering you all. Did so owning to the time constraint we have in front of us. GitHub has notified that actions that use set-output and Node v12 will not work after 31st May 2023. Refer:

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
https://github.blog/changelog/2023-05-04-github-actions-all-actions-will-run-on-node16-instead-of-node12/

**Review by EndBug — APPROVED** [review]
Hi 👋🏻 
The PR looks good to me, but as I mentioned in #9, I don't have write access to this repo, so I can't merge your PR.

The only thing I suggest is that, if you're using this action, you just switch the target to your fork

Also, this PR closes #9, closes #11, closes #12 (you have to write it this way to make GitHub close them automatically ;))

**Comment by wphromma** [comment]
Hi sorry for the late response and thanks for your contribution.
So, LGTM.
I will merge and release new vresion

**Comment by szmasood** [comment]
Hi, can this PR please be included in a new release?

**Comment by szmasood** [comment]
@wphromma any updates on release?

**Comment by cyberman54** [comment]
i opened issue #15 for this.

**Pull request merged**
